spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: eeve
    openai:
      embedding:
        options:
          model: text-embedding-3-large

logging:
  level:
    org.springframework.web.servlet: info
    org.springframework.web: debug
    org.springframework.boot: info
    com.hsik0225: debug
