spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: eeve

logging:
  level:
    org.springframework.web.servlet: info
    org.springframework.web: debug
    org.springframework.boot: info
    com.hsik0225: debug
